# Generated by Django 3.0.6 on 2020-05-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthdate',
            new_name='DOB',
        ),
    ]
